name: Firewall Policy Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Provider
        run: |
            go version
            go mod tidy
            # Clean old binary
            rm -f terraform-provider-fw-analyzer
        
            # Force fully static binary (CRITICAL)
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags="-s -w" -o terraform-provider-fw-analyzer
        
            chmod +x terraform-provider-fw-analyzer
        
            # Debug binary
            file terraform-provider-fw-analyzer
            ldd terraform-provider-fw-analyzer || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Create Global CLI Config
        run: |
          cat <<EOF > $HOME/.terraformrc
          provider_installation {
            dev_overrides {
              "local/fw-analyzer" = "$GITHUB_WORKSPACE"
            }
            direct {}
          }
          EOF
      - name: Test Provider Binary
        run: |
          echo "Running provider manually..."
          ./terraform-provider-fw-analyzer || true    

      - name: Terraform Init
        run: |
          export TF_CLI_CONFIG_FILE=$HOME/.terraformrc
          terraform init

      - name: Terraform Plan (Lint)
        run: |
          export TF_CLI_CONFIG_FILE=$HOME/.terraformrc
          terraform plan -no-color -detailed-exitcode
